### ISSUE TITLE
[FEATURE] Implement natural healing

### ISSUE THREAD

**Issue by marco-paulucci** [lambdaclass/curse_of_mirra#959]
## 🚀 Feature

The characters will periodically heal part of their health. 

Implementation:
- Characters heal 10% of their health per second
- The healing is interrupted for (config: 3000ms) after using an ability or being struck
- For VFX we can use the current healing anim

**Comment by tkz00** [comment]
This issue is currently on stand-by since we are yet to define the technical approach to it. The full logic for checking if the healing should apply updating the out of combat time of each player, reseting it on receiving damage or using a skill and checking if it's higher than the config defined value to start healing, is too costly to be run each tick. We are thinking about having an erlang process that starts healing the player, and sending it after the amount of time considered to be out of combat each time the player takes damage or activates a skill, and that each of these processes kills or overrides the previous one, since a player just took damage the previous healing process should not be activated.
